apiVersion : apps/v1
kind: Deployment
metadata:
  name: "poi"
  namespace: "api"  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "poi"
  template:
    metadata:
      labels:
        app: "poi"
    spec:
      containers:
        - name: "poi"
          image: "registrymdf7461.azurecr.io/poi:1.0"
          ports:
          - containerPort: 80