apiVersion : apps/v1
kind: Deployment
metadata:
  name: "user-java"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "user-java"
  template:
    metadata:
      labels:
        app: "user-java"
    spec:
      containers:
        - name: "user-java"
          image: "registrymdf7461.azurecr.io/user-java"
          ports:
          - containerPort: 80