apiVersion : apps/v1
kind: Deployment
metadata:
  name: "trips"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "trips"
  template:
    metadata:
      labels:
        app: "trips"
    spec:
      containers:
        - name: "trips"
          image: "registrymdf7461.azurecr.io/trips:1.0"
          ports:
          - containerPort: 80