# This is a SecretProviderClass example using aad-pod-identity to access Keyvault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sync
  namespace: api
spec:
  provider: azure
  secretObjects:                                 # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - secretName: fromvksecrets
    type: Opaque
    data: 
    - objectName: SQLPASSWORD                    # name of the mounted content to sync. this could be the object name or object alias 
      key: sqlpasswordkey
  parameters:
    usePodIdentity: 'false'                                                 
    useVMManagedIdentity: 'true'    
    userAssignedIdentityID: 73cd3a6a-6192-4846-82ba-5649942e6bf5          # Set to true for using aad-pod-identity to access keyvault
    keyvaultName: kv-prod-wus-trips       # Set to the name of your Azure Key Vault instance
    cloudName: ""                        # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SQLPASSWORD
          objectType: secret             # object types: secret, key or cert
          objectVersion: ""              # [OPTIONAL] object versions, default to latest if empty
    tenantId: 2393e7d5-bba7-48ce-9643-b79ffac1c78d