apiVersion: v1
kind: Service
metadata:
    name: "userprofile"
    namespace: "api"
    labels:
        app: "userprofile"
spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "userprofile"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: user
  namespace: "api"
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /api/user
        backend:
          serviceName: userprofile
          servicePort: 80
      - path: /api/user/healthcheck
        backend:
          serviceName: userprofile
          servicePort: 80          