apiVersion: v1
kind: Service
metadata:
    name: "poi"
    namespace: "api"
    labels:
        app: "poi"
spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "poi"