apiVersion: v1
kind: Service
metadata:
    name: "trips"
    namespace: "api"
    labels:
        app: "trips"
spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "trips"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: trips
  namespace: "api"
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /api/trips
        backend:
          serviceName: trips
          servicePort: 80
      - path: /api/trips/healthcheck
        backend:
          serviceName: trips
          servicePort: 80          