apiVersion: v1
kind: Service
metadata:
    name: "userprofile"
    labels:
        app: "userprofile"
spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "userprofile"