apiVersion: v1
kind: Service
metadata:
    name: "trips"
    labels:
        app: "trips"
spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "trips"