apiVersion: v1
kind: Service
metadata:
    name: "tripviewer"
    namespace: "web"
    labels:
        app: "tripviewer"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "tripviewer"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tripviewer
  namespace: "web"
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: tripviewer
          servicePort: 80   