apiVersion: v1
kind: Service
metadata:
    name: "poi"
    namespace: "api"
    labels:
        app: "poi"
spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "poi"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: poi
  namespace: "api"
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /api/poi
        backend:
          serviceName: poi
          servicePort: 80
      - path: /api/poi/healthcheck
        backend:
          serviceName: poi
          servicePort: 80